// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at, updated_at FROM "user"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, password, created_at, updated_at FROM "user"
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO "user" (
 id, email, password 
) VALUES ( uuid_generate_v4(), $1, $2 )
RETURNING id, email, password, created_at, updated_at
`

type RegisterUserParams struct {
	Email    string `binding:"required,email" example:"mosh@mail.com" json:"email"`
	Password string `binding:"required" example:"Hello" json:"password"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, registerUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
