// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID             int32
	Title          string
	Author         pgtype.Text
	PlublishedDate pgtype.Date
}
