// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetProfileByUserId(ctx context.Context, userID uuid.UUID) (*Profile, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (*User, error)
	InsertProfile(ctx context.Context, arg InsertProfileParams) (*Profile, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (*User, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (*Profile, error)
}

var _ Querier = (*Queries)(nil)
