// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	FindAllBooks(ctx context.Context) ([]*Book, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (*User, error)
	InsertBook(ctx context.Context, arg InsertBookParams) (*Book, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
